### ISSUE TITLE
Not working with Rythmbox 3.4.3

### ISSUE THREAD

**Issue by germanfr** [fossfreedom/alternative-toolbar#144]
When I start Rhythmbox the plugin doesn't seem to load, and I get this trace:

```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 174, in do_activate
    self.toolbar_type.initialise(self)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1330, in initialise
    self._setup_playbar()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1391, in _setup_playbar
    action.set_active(True)
AttributeError: 'NoneType' object has no attribute 'set_active'

(rhythmbox:3372): Rhythmbox-WARNING **: 18:33:13.763: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.MediaKeys was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 160, in delayed
    self.on_startup()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1353, in on_startup
    super(AltToolbarHeaderBar, self).on_startup(*args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 781, in on_startup
    super(AltToolbarShared, self).on_startup(*args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 193, in on_startup
    self.reset_toolbar(self.shell.props.selected_page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1598, in reset_toolbar
    self._set_toolbar_controller()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1620, in _set_toolbar_controller
    current_controller.update_controls(self.shell.props.selected_page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py", line 202, in update_controls
    self.header.set_library_box_sensitive(True)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1631, in set_library_box_sensitive
    self.library_box.set_sensitive(sensitive)
AttributeError: 'AltToolbarHeaderBar' object has no attribute 'library_box'
```

And this is my config:

```
dconf dump /org/gnome/rhythmbox/plugins/alternative_toolbar/
[/]
dark-theme=true
display-type=1
expanders='{1: True, 2: True, 0: False, 3: False}'
show-source-toolbar=false
show-tooltips=false
volume-control=true
```

I can provide more info if needed.

**Comment by fossfreedom** [comment]
What version of linux are you using and what version of the plugin are you using?

**Comment by germanfr** [comment]
Oh, I was using an old version `0.18.1`. I re-installed it and it works in version `0.18.4`. I thought I had the latest version, but the -git package from the AUR doesn't seem to update automatically. Sorry.
